version: 2
updates:
  - package-ecosystem: "gradle" # Gradle for Java/Kotlin projects
    directory: "/3.5.0/app" # Path to the directory containing build.gradle
    schedule:
      interval: "weekly"

